#!/usr/bin/env ansible-playbook -i install/hosts

- hosts: ubuntu1
  sudo: yes

  vars:
    SERVER_NAME: ubuntu1
    SITE: moinmoin
    WIKI_USER: moinmoin
    VENV_HOME: /usr/local/share/virtualenvs
    VENV_BASE: "{{ VENV_HOME }}/base-env"
    VENV_SITE: "{{ VENV_HOME }}/{{ SITE }}-env"
    SITE_DIR: "/var/www/{{ SITE }}"
    STATIC_DIR: "/var/www/{{ SITE }}-static"
    WSGI_FILE: moin.wsgi
    DATA_DIR: "/home/{{ SITE }}"

  tasks:
  - name: install system packages
    apt: pkg={{ item }}
    with_items:
      - apache2
      - libapache2-mod-wsgi
      - python-pip
      - tree

  - name: install python packages
    pip: name={{item}} state=latest
    with_items:
      - pip
      - virtualenv
      - wheel

  - name: create directories
    file: path={{ item }} state=directory owner=root group=root mode=755
    with_items:
      - "{{ VENV_HOME }}"
      - "{{ SITE_DIR }}"
      - "{{ STATIC_DIR }}"
      - "{{ DATA_DIR }}"

  - name: create virtualenvs
    command: virtualenv {{ item }}
    with_items:
      - "{{ VENV_BASE }}"
      - "{{ VENV_SITE }}"

  - name: install moinmoin and other dependencies to the virtualenv
    pip: virtualenv={{ VENV_SITE }} name={{item}}
    with_items:
      - moin

  # web assets
  - name: copy wsgi script
    template: src=templates/{{ WSGI_FILE }} dest={{ SITE_DIR }}/{{ WSGI_FILE }}
              mode=644
    notify:
      - restart apache

  - name: copy static assets
    command: cp -r {{ VENV_SITE }}/lib/python2.7/site-packages/MoinMoin/web/static/htdocs \
             {{ STATIC_DIR }}

  - name: create config for site
    template: src=templates/apache.conf
              dest=/etc/apache2/sites-available/{{ SITE }}.conf
              mode=644
    notify:
      - enable site
      - restart apache

  - name: create wiki user to house wiki data and config
    user: name={{ WIKI_USER }} shell=/bin/false

  - name: copy the wiki data from the installed package
    shell: test -d {{ DATA_DIR }}/{{ item }} || \
           cp -r {{ VENV_SITE }}/share/moin/{{ item }} {{ DATA_DIR }}
    with_items:
      - data
      - underlay

  - name: fix ownership of data and underlay
    file: path={{ DATA_DIR }}/{{ item }}
          state=directory owner=www-data group=www-data mode=u+rw recurse=yes
    with_items:
      - data
      - underlay

  - name: install wikiconfig.py
    template: src=templates/wikiconfig.py
              dest={{ DATA_DIR }}/wikiconfig.py
    notify:
      - restart apache

  handlers:

  - name: enable site
    command: a2ensite {{ SITE }}

  - name: restart apache
    command: service apache2 restart
